### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: request is not a function

### ISSUE THREAD

**Issue by HeeroS03** [islizeqiang/electron-request#2]
I'm getting this error using the example

import request from 'electron-request';

void (async () => {
  const url = 'https://github.com/';
  const defaultOptions = {
    method: 'GET',
    body: null,
    followRedirect: true,
    maxRedirectCount: 20,
    timeout: 0,
    size: 0,
  };
  const response = await request(url, defaultOptions);
  const text = await response.text();
})();

**Comment by islizeqiang** [comment]
Hi, thanks for your interest. I fixed it in [78b7e30](https://github.com/islizeqiang/electron-request/commit/78b7e30c6d371c3d7abba253d1497c0665dd1752)
