### ISSUE TITLE
get请求查询参数丢失

### ISSUE THREAD

**Issue by zhixinpeng** [islizeqiang/electron-request#6]
发起一个get请求，携带query，我已经断点查询到 options 中的 path 为 '/api?count=2'，但实际发出去的请求只有 '/api'，查询参数丢失了，这是怎么回事？

**Comment by zhixinpeng** [comment]
![image](https://user-images.githubusercontent.com/24643457/154408675-ade84e18-9351-426c-bfc2-39c3768d3760.png)
![image](https://user-images.githubusercontent.com/24643457/154408729-35f174c1-0b89-494e-968c-369fb7e82f23.png)
图1可行，图2不可行

**Comment by islizeqiang** [comment]
这可能是 electron 中的 [ClientRequest](https://www.electronjs.org/docs/latest/api/client-request) 实现的问题。我将 [path 参数拼接到 url 参数上](https://github.com/islizeqiang/electron-request/commit/7061d168dc91988beda62c58eb1ab3a72dc20af5)解决了这个问题，并发布了新的版本。你可以重新安装再次尝试下。

**Comment by zhixinpeng** [comment]
感谢

**Comment by zhixinpeng** [comment]
我试了一下 好像没有考虑到post请求的兼容性， 我发送post 到 http://api.com/token，结果发送到了 http://api.com/token/token
